<?php
/** Printable sale / purchase bill. In layout.php. */
$inv    = $inv ?? [];
$items  = $inv['items'] ?? [];
$isSale = ($inv['type'] ?? 'sale') === 'sale';
$firm   = $company['name'] ?? 'Hissab-Kitaab';
$money  = static fn ($v): string => '₹' . number_format((float) $v, 2);
$modes  = ['cash' => 'Cash', 'bank' => 'Bank', 'upi' => 'UPI', 'cheque' => 'Cheque', 'card' => 'Card'];
?>
<div class="d-flex justify-content-end gap-2 mb-3 d-print-none">
    <a href="<?= site_url('invoices') ?>" class="btn btn-sm btn-outline-secondary"><i class="bi bi-arrow-left me-1"></i>Back</a>
    <button class="btn btn-sm btn-primary" onclick="window.print()"><i class="bi bi-printer me-1"></i>Print / Save PDF</button>
</div>

<div class="card">
    <div class="card-body" id="billArea" style="max-width:820px;margin:0 auto;">
        <div class="d-flex justify-content-between align-items-start" style="border-bottom:3px solid #0b2f73;padding-bottom:12px;">
            <div>
                <div style="font-size:12px;font-weight:800;letter-spacing:.06em;color:#0b2f73;text-transform:uppercase;"><?= esc($firm) ?></div>
                <div style="font-size:24px;font-weight:900;color:#0b2f73;"><?= $isSale ? 'Sale Bill' : 'Purchase Bill' ?></div>
            </div>
            <div class="text-end">
                <div style="font-size:17px;font-weight:900;"><?= esc($inv['invoice_no']) ?></div>
                <div class="text-muted"><?= esc($inv['invoice_date']) ?></div>
            </div>
        </div>

        <div class="d-flex justify-content-between my-3">
            <div>
                <div class="text-muted" style="font-size:11px;font-weight:700;text-transform:uppercase;"><?= $isSale ? 'Bill To' : 'Bill From' ?></div>
                <div style="font-size:16px;font-weight:800;"><?= esc($inv['party_name'] ?: ($isSale ? 'Cash Sale' : 'Cash Purchase')) ?></div>
            </div>
            <div class="text-end text-muted">
                <div>Payment: <b class="text-dark"><?= esc($modes[$inv['payment_mode']] ?? ucfirst((string) $inv['payment_mode'])) ?></b></div>
            </div>
        </div>

        <table class="table table-sm table-bordered">
            <thead style="background:#0b2f73;color:#fff;">
                <tr>
                    <th style="width:40px">#</th><th>Item</th>
                    <th class="text-end" style="width:90px">Qty</th>
                    <th class="text-end" style="width:110px">Rate</th>
                    <th class="text-end" style="width:80px">Tax</th>
                    <th class="text-end" style="width:120px">Amount</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($items as $k => $it): ?>
                <tr>
                    <td><?= $k + 1 ?></td>
                    <td><?= esc($it['name']) ?></td>
                    <td class="text-end"><?= rtrim(rtrim((string) $it['qty'], '0'), '.') ?></td>
                    <td class="text-end"><?= $money($it['rate']) ?></td>
                    <td class="text-end"><?= ((float) $it['tax_rate']) ? $it['tax_rate'] . '%' : '—' ?></td>
                    <td class="text-end fw-bold"><?= $money($it['amount']) ?></td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <div class="d-flex justify-content-end">
            <table style="min-width:280px">
                <tr><td class="text-muted py-1">Subtotal</td><td class="text-end py-1"><?= $money($inv['subtotal']) ?></td></tr>
                <?php if ((float) $inv['tax_total']): ?>
                <tr><td class="text-muted py-1">Tax</td><td class="text-end py-1"><?= $money($inv['tax_total']) ?></td></tr>
                <?php endif; ?>
                <?php if ((float) $inv['discount']): ?>
                <tr><td class="text-muted py-1">Discount</td><td class="text-end py-1">- <?= $money($inv['discount']) ?></td></tr>
                <?php endif; ?>
                <tr style="border-top:2px solid #0b2f73;">
                    <td class="py-2 fw-bold fs-5">Grand Total</td>
                    <td class="text-end py-2 fw-bold fs-5" style="color:#0b2f73;"><?= $money($inv['total']) ?></td>
                </tr>
            </table>
        </div>

        <?php if (! empty($inv['notes'])): ?>
        <div class="text-muted mt-3"><b>Notes:</b> <?= esc($inv['notes']) ?></div>
        <?php endif; ?>
        <div class="text-center text-muted mt-4" style="font-size:11px;">Generated by Hissab-Kitaab · computer-generated bill</div>
    </div>
</div>
