<?php

/**
 * sms_helper — CI4 port of the CI3 MSG91 SMS stack (function_helper.php).
 * Used by the Auth forgot-password flow to text a temporary password, and is
 * reusable for the other transactional templates. Keeps the exact CI3 template
 * ids, variable maps, normalisation and Flow API call so behaviour matches 1:1.
 */

if (! defined('MSG91_AUTH_KEY')) {
    define('MSG91_AUTH_KEY', getenv('MSG91_AUTH_KEY') ? getenv('MSG91_AUTH_KEY') : '492391AxqhluVw1B3p698574c5P1');
}
if (! defined('MSG91_FLOW_URL')) {
    define('MSG91_FLOW_URL', 'https://control.msg91.com/api/v5/flow');
}

if (! function_exists('generate_password')) {
    function generate_password()
    {
        // CI3: random_string('numeric', 6)
        $out = '';
        for ($i = 0; $i < 6; $i++) {
            $out .= (string) random_int(0, 9);
        }
        return $out;
    }
}

if (! function_exists('msg91_sms_templates')) {
    function msg91_sms_templates($template_type = null)
    {
        $templates = [
            'gstBasedTaxInvoice' => [
                'template_id' => '6996cb72a9ba3d92f70eb502',
                'content' => 'Dear ##var1##, E-Invoice ##var2## dated ##var3## has been generated by CR Industries (Manufacturing & Trading Unit). Product: ##var4## | Qty: ##var5## ##var6## Rate: ₹##var7## | Tax: ₹##var8## Freight: ₹##var9## | Advance: ₹##var10## Total Invoice Amount: ₹##var11## This is an automated billing notification from CR Industries.',
                'variables' => ['name', 'invoice_no', 'invoice_date', 'product', 'quantity', 'unit', 'rate', 'tax', 'freight', 'advance', 'total_invoice_amount'],
            ],
            'NewAccountRegistration' => [
                'template_id' => '6996caf29b6869b27a0ab3d2',
                'content' => 'Dear ##var1##, Your account has been successfully registered with CR Industries (Manufacturing & Trading Unit). GST: ##var2## State: ##var3## | City: ##var4## Bank: ##var5## Status: ##var6## This is an automated system notification from CR Industries.',
                'variables' => ['name', 'gst', 'state', 'city', 'bank', 'status'],
            ],
            'TemplateActivation' => [
                'template_id' => '6996ca9c5e94f209380876d3',
                'content' => 'Dear ##var3##, Template ##var1## for Financial Year ##var2## has been activated for C.R. INDUSTRIES (Manufacturing & Trading Unit). This is an automated system notification from C.R. INDUSTRIES.',
                'variables' => ['template', 'financial_year', 'name'],
            ],
            'StockSummary' => [
                'template_id' => '6996ca4934421fa7a30fb4d2',
                'content' => 'Stock Update – C.R. INDUSTRIES (Manufacturing & Trading Unit) Commodity: ##var1## Closing Stock: ##var2## Qntl Month: ##var3## This is an automated system notification from C.R. INDUSTRIES',
                'variables' => ['commodity', 'closing_stock', 'month'],
            ],
            'LedgerBalanceInquiry' => [
                'template_id' => '6996be0f18253ba56e08cf72',
                'content' => 'Dear ##var1##, Account Summary – CR Industries (Manufacturing & Trading Unit) Cash Balance: ₹##var2## Farmers Balance: ₹##var3## Total Balance: ₹##var4## Total Credit: ₹##var5## Total Debit: ₹##var6## Outstanding: ₹##var7## Total Registered Farmers: ##var8## This is an automated system notification from CR Industries.',
                'variables' => ['name', 'cash_balance', 'farmers_balance', 'total_balance', 'total_credit', 'total_debit', 'outstanding', 'total_registered_farmers'],
            ],
            'WelcomeWithName' => [
                'template_id' => '699577d43ee7f211f708c922',
                'content' => 'Hello ##var1##, Your Default Password is ##var2##, CR Industries',
                'variables' => ['name', 'password'],
            ],
            'AccountStatusChange' => [
                'template_id' => '699577a83ca652bd7f0899d2',
                'content' => 'CR IND, Your Account Status is Changed Current Status is ##var1##',
                'variables' => ['status'],
            ],
            'Password' => [
                'template_id' => '699577836a8513a8980aebb2',
                'content' => 'Welcome CR Industries, Your Default Password is ##var1##',
                'variables' => ['password'],
            ],
            'WelcomeTemplate' => [
                'template_id' => '69957756ffe501c16a019972',
                'content' => 'Welcome To CR Industries, Your Account is active now login your account using your email and password is ##var1##',
                'variables' => ['password'],
            ],
            'AddedLotInSystem' => [
                'template_id' => '699576f4f34164e2920d3884',
                'content' => 'Lot No: ##var1## Center: ##var2## Challan No: ##var3## Truck: ##var4## | Driver: ##var5## Bags: ##var6## | Loaded Wt: ##var7## Blank Wt: ##var8## | Moisture: ##var9## | Broken: ##var10## Mill: ##var11## | Status: ##var12## Dispatch Date: ##var13## CR Industries (Manufacturing & Trading Unit)',
                'variables' => ['lot_no', 'center', 'challan_no', 'truck', 'driver', 'bags', 'loaded_weight', 'blank_weight', 'moisture', 'broken', 'mill', 'status', 'dispatch_date'],
            ],
            'Trading_Material_Variety' => [
                'template_id' => '6995761fa43881a574072a03',
                'content' => 'Dear ##var1##, Potato variety ##var2## added successfully to the inventory system of CR Industries (Manufacturing & Trading Unit). Technical Name: ##var3##. Seed Class: ##var4##. Added By: ##var5## on ##var6##. CR Industries',
                'variables' => ['name', 'potato_variety', 'technical_name', 'seed_class', 'added_by', 'added_on'],
            ],
            'AccountAdded' => [
                'template_id' => '699575e57ca05d390009e062',
                'content' => 'Dear ##var1##, Your account ##var2## has been successfully created with CR Industries (Manufacturing & Trading Unit) on ##var3## at ##var4##. For assistance, please contact CR Industries support team. CR Industries',
                'variables' => ['name', 'account', 'date', 'time'],
            ],
            'TaxInvoiceInformation' => [
                'template_id' => '69957590b2469d02e60d5b72',
                'content' => 'Dear ##var1##, Your invoice ##var2## for goods/services supplied by CR Industries (Manufacturing & Trading Unit) has been updated successfully. Revised payable amount: ₹##var3##. For invoice details, please contact CR Industries at ##var4##. CR Industries',
                'variables' => ['name', 'invoice_no', 'revised_payable_amount', 'contact'],
            ],
            'Taxinvoice' => [
                'template_id' => '6995752b7a29a525c70153d2',
                'content' => 'Dear ##var1##, Your tax invoice ##var2## dated ##var3## has been generated for goods/services supplied by CR Industries (Manufacturing & Trading Unit). Total payable amount: ₹##var4##. For queries, please contact CR Industries support team. CR Industries',
                'variables' => ['name', 'invoice_no', 'invoice_date', 'total_payable_amount'],
            ],
            'welcomeBackUser' => [
                'template_id' => '699574def5278eabe10451d2',
                'content' => 'Welcome back, ##var1##. You have successfully logged into the Dashboard of CR Industries (Manufacturing & Trading Unit) on ##var2## at ##var3##. If this was not you, please contact our support team immediately. CR Industries',
                'variables' => ['name', 'date', 'time'],
            ],
            'OTP' => [
                'template_id' => '698afc17aade65720b6c04e7',
                'content' => 'Welcome To CR Industries, Your OTP is ##var1##',
                'variables' => ['otp'],
            ],
            'ChangePassword' => [
                'template_id' => '6985abc952db7141101cbf45',
                'content' => 'Welcome To CR Industries, Your Account password is changed, If you are not aware of that contact to Admin',
                'variables' => [],
            ],
            'Login_OTP' => [
                'template_id' => '69835dccc639566a40283d2c',
                'content' => 'Your Login OTP Code is ##var1##',
                'variables' => ['otp'],
            ],
        ];

        if ($template_type === null) {
            return $templates;
        }

        return isset($templates[$template_type]) ? $templates[$template_type] : false;
    }
}

if (! function_exists('msg91_normalize_mobile')) {
    function msg91_normalize_mobile($mobile, $country_code = '91')
    {
        $mobile = preg_replace('/\D+/', '', (string) $mobile);
        $mobile = ltrim($mobile, '0');

        if (strpos($mobile, $country_code) !== 0) {
            return $country_code . $mobile;
        }

        return $mobile;
    }
}

if (! function_exists('msg91_template_vars')) {
    function msg91_template_vars($template_type, $message_data = [])
    {
        $template = msg91_sms_templates($template_type);
        if (! $template) {
            return [];
        }
        if (! is_array($message_data)) {
            $message_data = [$message_data];
        }

        $vars = [];
        foreach ($template['variables'] as $index => $name) {
            $position = $index + 1;
            $value = '';

            if (array_key_exists($name, $message_data)) {
                $value = $message_data[$name];
            } elseif (array_key_exists('var' . $position, $message_data)) {
                $value = $message_data['var' . $position];
            } elseif (array_key_exists($index, $message_data)) {
                $value = $message_data[$index];
            } elseif (array_key_exists($position, $message_data)) {
                $value = $message_data[$position];
            }

            $value = (string) $value;
            $vars['var' . $position] = $value;
            $vars['VAR' . $position] = $value;
        }

        return $vars;
    }
}

if (! function_exists('msg91_ca_bundle_path')) {
    function msg91_ca_bundle_path()
    {
        $paths = [
            FCPATH . 'assets/ckfinder/core/connector/php/vendor/guzzle/guzzle/src/Guzzle/Http/Resources/cacert.pem',
            'D:/xampp/perl/vendor/lib/Mozilla/CA/cacert.pem',
            'D:/xampp/phpMyAdmin/libraries/certs/cacert.pem',
        ];
        foreach ($paths as $path) {
            if (is_file($path) && is_readable($path)) {
                return $path;
            }
        }
        return false;
    }
}

if (! function_exists('msg91_debug_log')) {
    function msg91_debug_log($result)
    {
        $log_dir = WRITEPATH . 'logs';
        if (! is_dir($log_dir) || ! is_writable($log_dir)) {
            return false;
        }

        $safe_result = $result;
        if (isset($safe_result['payload']['recipients'])) {
            foreach ($safe_result['payload']['recipients'] as $key => $recipient) {
                if (isset($recipient['mobiles'])) {
                    $mobile = (string) $recipient['mobiles'];
                    $safe_result['payload']['recipients'][$key]['mobiles'] = strlen($mobile) > 4
                        ? str_repeat('*', strlen($mobile) - 4) . substr($mobile, -4)
                        : '****';
                }
            }
        }

        $line = '[' . date('Y-m-d H:i:s') . '] ' . json_encode($safe_result) . PHP_EOL;
        return (bool) file_put_contents($log_dir . '/msg91_sms_debug-' . date('Y-m-d') . '.log', $line, FILE_APPEND);
    }
}

if (! function_exists('msg91_send_template')) {
    function msg91_send_template($mobile, $template_type, $message_data = [], $options = [])
    {
        $template = msg91_sms_templates($template_type);
        if (! $template) {
            return ['status' => false, 'message' => 'Invalid MSG91 template type: ' . $template_type];
        }

        $recipient = array_merge(
            ['mobiles' => msg91_normalize_mobile($mobile)],
            msg91_template_vars($template_type, $message_data)
        );

        $payload = [
            'template_id' => $template['template_id'],
            'short_url' => isset($options['short_url']) ? (string) $options['short_url'] : '0',
            'recipients' => [$recipient],
        ];
        if (isset($options['realTimeResponse'])) {
            $payload['realTimeResponse'] = (string) $options['realTimeResponse'];
        }

        $curl = curl_init();
        $curl_options = [
            CURLOPT_URL => MSG91_FLOW_URL,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => '',
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 30,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => 'POST',
            CURLOPT_POSTFIELDS => json_encode($payload),
            CURLOPT_HTTPHEADER => [
                'accept: application/json',
                'authkey: ' . MSG91_AUTH_KEY,
                'content-type: application/json',
            ],
        ];

        $ca_bundle = msg91_ca_bundle_path();
        if ($ca_bundle) {
            $curl_options[CURLOPT_CAINFO] = $ca_bundle;
        }

        curl_setopt_array($curl, $curl_options);
        $response = curl_exec($curl);
        $error = curl_error($curl);
        $http_code = curl_getinfo($curl, CURLINFO_HTTP_CODE);
        curl_close($curl);

        if ($error) {
            return ['status' => false, 'message' => 'cURL Error: ' . $error, 'payload' => $payload];
        }

        $decoded_response = json_decode($response, true);
        $response_data = $decoded_response ?: $response;
        $response_type = is_array($decoded_response) && isset($decoded_response['type']) ? strtolower($decoded_response['type']) : '';
        $is_success = ($http_code >= 200 && $http_code < 300 && $response_type !== 'error');

        $result = [
            'status' => $is_success,
            'http_code' => $http_code,
            'message' => is_array($decoded_response) && isset($decoded_response['message']) ? $decoded_response['message'] : null,
            'response' => $response_data,
            'payload' => $payload,
        ];

        msg91_debug_log($result);
        return $result;
    }
}
